---
kind: pipeline
name: windows-1909-info

platform:
  os: windows
  arch: amd64
  version: 1909

steps:
  - name: info-pr
    image: mcr.microsoft.com/windows/servercore:1909
    commands:
      - systeminfo
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag
      instance:
        - drone-pr.rancher.io
  - name: info-publish
    image: mcr.microsoft.com/windows/servercore:1909
    commands:
      - systeminfo
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag
      instance:
        - drone-publish.rancher.io
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
name: pr-nested-lxc

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag
  instance:
     - drone-pr.rancher.io

node:
  eio: test
