---
kind: pipeline
name: windows-1903-info

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
  - name: info
    image: mcr.microsoft.com/windows/servercore:1903
    commands:
      - systeminfo
      - docker.exe info
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

---
kind: pipeline
name: windows-1903

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
  - name: build
    pull: always
    image: maiwj/dapper:windows-1903
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
      - promote
