---
kind: pipeline
name: windows-1909-info

platform:
  os: windows
  arch: amd64
  version: 1909

steps:
  - name: info
    image: mcr.microsoft.com/windows/servercore:1909
    commands:
      - systeminfo
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
      - promote
